language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10
# command to install dependencies
install: 
  - pip install Django==$DJANGO_VERSION
  - pip install -e .[dev]
# command to run tests
script: pytest
